import { expect } from "chai";
import { ImageNoteGenerator } from "../src/modules/imageNoteGenerator";

type ImageNoteFormatter = {
  formatImageNoteContentWithAttachment(
    itemTitle: string,
    attachmentKey: string,
    lang?: "zh" | "en",
  ): string;
};

describe("ImageNoteGenerator bilingual notes", function () {
  const formatter = ImageNoteGenerator as unknown as ImageNoteFormatter;

  it("renders Chinese image-summary notes by default", function () {
    const html = formatter.formatImageNoteContentWithAttachment(
      "Paper",
      "ATTACHMENT",
    );

    expect(html).to.include("AI 管家一图总结 - Paper");
    expect(html).to.include('alt="学术概念海报"');
  });

  it("renders fully English image-summary note framing", function () {
    const html = formatter.formatImageNoteContentWithAttachment(
      "Paper",
      "ATTACHMENT",
      "en",
    );

    expect(html).to.include("AI Image Summary - Paper");
    expect(html).to.include('alt="Academic concept poster"');
    expect(html).to.include("generated by AI Butler");
    expect(html).not.to.include("一图总结");
  });
});
